server {
    server_name  mongo-express.local; # nom de domaine pour accéder à mongo-express

    access_log  /var/log/nginx/mongo-express.access.log  main;

    # redirection vers le service mongo-express
    location / {
        proxy_pass http://mongo-express:8081; # redirection vers le service mongo-express
        proxy_set_header Host $host; # transmission de l'en-tête Host
        proxy_set_header X-Real-IP $remote_addr; # transmission de l'adresse IP du client
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # transmission de la chaîne d'adresses IP pour le suivi des clients
        proxy_set_header X-Forwarded-Proto $scheme; # transmission du protocole utilisé (HTTP ou HTTPS)
        index  index.html index.htm;
    }
}

